before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/pingtunnel/main.go
    ldflags:
      - "-s -w"
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_386
      - linux_amd64
      - linux_amd64_v3
      # - linux_arm_5
      - linux_arm_6
      - linux_arm_7
      - linux_arm64
      # - linux_mips_softfloat
      # - linux_mips_hardfloat
      # - linux_mipsle_softfloat
      # - linux_mipsle_hardfloat
      # - linux_mips64
      # - linux_mips64le
      # - linux_s390x
      # - linux_riscv64
      # - freebsd_386
      # - freebsd_amd64
      - windows_386
      - windows_amd64
      - windows_amd64_v3
      - windows_arm64

archives:
  - wrap_in_directory: true
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      amd64: 64-bit
      386: 32-bit
      arm: ARM
      arm64: ARM64
      darwin: macOS
      linux: Linux
      windows: Windows
      openbsd: OpenBSD
      netbsd: NetBSD
      freebsd: FreeBSD
checksum:
  name_template: "checksums.txt"
release:
  draft: true
  prerelease: auto
  name_template: "{{.ProjectName}}-v{{.Version}}-{{.Date}}"