env:
  - GO111MODULE=on

builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/pingtunnel/main.go
    ldflags:
      - "-s -w"
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - "386"
      - amd64
      - arm64
archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}_v{{ .Arm }}{{ end }}{{ with .Mips }}_{{ .Mips }}{{ end }}"
    format: tar.gz
    files:
      - none*
    format_overrides:
      - goos: windows
        format: zip
    wrap_in_directory: true
    replacements:
      amd64: 64-bit
      386: 32-bit
      arm: ARM
      arm64: ARM64
      darwin: macOS
      linux: Linux
      windows: Windows
      openbsd: OpenBSD
      netbsd: NetBSD
      freebsd: FreeBSD
release:
  draft: true
  prerelease: auto
  name_template: "{{.ProjectName}}-v{{.Version}}-{{.Date}}"
